=== TunnelSnakesRule/BasicXML/Data/Hooah.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- a Shcedule has a week-->

<!-- a week has days-->
<!ELEMENT week (day+)>
<!-- a day has slots-->
<!ELEMENT day (weekslot+)>
<!-- the diffrent days-->
<!ATTLIST day
    which (mon|tue|wed|thu|fri) #REQUIRED
  >
<!-- Slots have instructors and thier  class number-->
<!ELEMENT weekslot (instructor,room)>
<!-- diifrent possible times and courses -->
<!ATTLIST weekslot
    time (0830|0930|1030|1130|1230|1330|1430|1530|1630) #REQUIRED
    class (ACIT4620|ACIT4650|ACIT4660|ACIT4770|ACIT4850|ACIT4910) #REQUIRED
  >
<!--enter in instructore-->
<!ELEMENT instructor (#PCDATA)>
<!--enter in room #-->
<!ELEMENT room (#PCDATA)>





<!ELEMENT time (timeslot+)>
<!ATTLIST time
    which (0830|0930|1030|1130|1230|1330|1430|1530|1630) #REQUIRED
  >

<!ELEMENT timeslot (instructor,room)>
<!ATTLIST timeslot
    day (Monday|Tuesday|Wednesday|Thursday|Friday) #REQUIRED
    class (ACIT4620|ACIT4650|ACIT4660|ACIT4770|ACIT4850|ACIT4910) #REQUIRED
  >




<!ELEMENT class (classslot+)>
<!ATTLIST class
    which (ACIT4620|ACIT4650|ACIT4660|ACIT4770|ACIT4850|ACIT4910) #REQUIRED
  >

<!ELEMENT classslot (instructor,room)>
<!ATTLIST classslot
    day (Monday|Tuesday|Wednesday|Thursday|Friday) #REQUIRED
    time (0830|0930|1030|1130|1230|1330|1430|1530|1630) #REQUIRED
  >

=== TunnelSnakesRule/BasicXML/Data/class.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE class SYSTEM 'Hooah.dtd'>


<class which="ACIT4910">
    <classslot day="Monday" time="1530">
           
        <instructor>Richard Chau</instructor>
        <room>SW9-206</room>
    </classslot>
    <classslot day="Thursday" time="0930">
           
        <instructor>Richard Chau</instructor>
        <room>SW5-1840</room>
    </classslot>
    <classslot day="Thursday" time="1030">
            
        <instructor>Richard Chau</instructor>
        <room>SE12-306</room>
    </classslot>
    <classslot day="Thursday" time="1130">
   
        <instructor>Richard Chau</instructor>
        <room>SE12-306</room>
    </classslot>
</class>
